# microservice cadastro - eureka client
spring:
  application:
    name: mscadastros

  datasource: 
    url: jdbc:mysql://127.0.0.1:3306/dbcadastro
    username: root 
    password: root 
    driver-class-name: com.mysql.cj.jdbc.Driver 
  jpa: 
    hibernate: 
      ddl-auto: update 
    show-sql: true 
    properties: 
      hibernate: 
      dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 3030



eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}